import torch
tensorA = torch.rand(5,5,device="cpu")
tensorB = torch.rand(5,5,device="cpu")
tensorMul = torch.matmul(tensorA, tensorB)
tensorARGMIN= torch.argmin(tensorMul)
tensorMIN = torch.min(tensorMul)
tensorMAX = torch.max(tensorMul)
tensorAVG = torch.mean(tensorMul)
tensorSUM = torch.sum(tensorMul)
print(tensorMul)
print(f'Minimum Value is {tensorMIN}')
print(f'Maximum Value is {tensorMAX}')
print(f'Average Value is {tensorAVG}')
print(f'Maximum Value is {tensorMAX}')
print(f'Index Of Minumum Value is {tensorARGMIN}')
print(f'Sum Value is {tensorSUM}')
